"""empty message

Revision ID: 30354a8a2f03
Revises: 4d33fa548cd5
Create Date: 2022-06-03 14:54:15.356115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30354a8a2f03'
down_revision = '4d33fa548cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('wantVenue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('wantTalent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'wantTalent')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'wantVenue')
    op.drop_column('Artist', 'website_link')
    op.drop_table('shows')
    # ### end Alembic commands ###
