"""empty message

Revision ID: 4d33fa548cd5
Revises: 
Create Date: 2022-06-03 03:08:37.581699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d33fa548cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'description')
    op.drop_column('Venue', 'talent')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###
